"""
Seed a small knowledge base and embed it — INSIDE Oracle when an ONNX model is
loaded (zero external calls), otherwise via OpenAI as a fallback.

Run:  python src/seed.py
"""
from __future__ import annotations

import asyncio

from openai import AsyncOpenAI

import config
from embeddings import indb_model_available, indb_embed_expr, sql_str, vector_literal
from mcp_oracle import open_oracle_mcp, OracleMCP

# title, content  (a self-referential Oracle 26ai knowledge base)
DOCS = [
    ("SQLcl MCP Server",
     "The SQLcl MCP Server lets AI assistants and scripts run SQL against Oracle Database over "
     "the Model Context Protocol. Start it with 'sql -mcp'. It uses a saved connection, so the AI "
     "never sees your password, and every statement it runs is captured in the database audit "
     "trail. This is the safe way to let an AI assistant query your database."),
    ("AI Vector Search",
     "Oracle AI Vector Search stores the semantic meaning of text as a VECTOR data type and finds "
     "similar items with VECTOR_DISTANCE using metrics like COSINE. Approximate nearest-neighbour "
     "queries use FETCH APPROX FIRST n ROWS ONLY, accelerated by HNSW or IVF vector indexes."),
    ("In-database embeddings with ONNX",
     "You can load an ONNX embedding model into the database with DBMS_VECTOR.LOAD_ONNX_MODEL and "
     "then call VECTOR_EMBEDDING(model USING text AS data) to generate embeddings inside Oracle. "
     "Because the text is embedded in the database, your documents never leave it — ideal for "
     "private or regulated data."),
    ("Select AI",
     "Select AI (DBMS_CLOUD_AI) lets the database translate natural-language questions into SQL "
     "using a configured LLM profile, and can also run retrieval-augmented generation. It is "
     "configured with an AI profile and a credential."),
    ("JSON Relational Duality",
     "JSON Relational Duality Views let you work with the same data as both rows and JSON "
     "documents. Apps get document-style access while the data stays in normalized tables with "
     "full SQL, transactions, and constraints."),
    ("SQL Firewall",
     "Oracle SQL Firewall inspects SQL inside the database and can allow-list the exact statements "
     "an account may run, blocking anomalous or injected SQL. It pairs well with AI-generated SQL "
     "to guarantee only approved statements execute."),
]


async def _run(mcp: OracleMCP, sql: str, what: str) -> None:
    out = await mcp.run_sql(sql)
    if "ORA-" in out or "Error" in out or "cancelled" in out:
        ora = next((ln for ln in out.splitlines() if "ORA-" in ln), out[:400])
        raise RuntimeError(f"{what} FAILED:\n{ora}")
    print(f"  · {what}")


async def main() -> None:
    async with open_oracle_mcp(config.SQLCL_COMMAND, config.ORACLE_MCP_CONNECTION) as mcp:
        print(f"Connected via SQLcl MCP (connection '{config.ORACLE_MCP_CONNECTION}').")
        await mcp.run_sqlcl("set define off")

        indb = await indb_model_available(mcp)
        mode = "IN-DATABASE (VECTOR_EMBEDDING)" if indb else "FALLBACK (OpenAI client-side)"
        print(f"Embedding mode: {mode}\n")

        print("Creating documents table ...")
        await mcp.run_sql("BEGIN EXECUTE IMMEDIATE 'DROP TABLE documents CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;")
        await _run(mcp,
            "CREATE TABLE documents (doc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "title VARCHAR2(160), content VARCHAR2(4000), embedding VECTOR(*, FLOAT32))",
            "documents")

        print("Inserting documents ...")
        # one INSERT per row — INSERT ALL evaluates an identity column only once per
        # statement, which collides on the doc_id primary key.
        for (t, c) in DOCS:
            await _run(mcp, f"INSERT INTO documents (title, content) VALUES ({sql_str(t)},{sql_str(c)})",
                       f"doc: {t}")

        if indb:
            print("Embedding documents INSIDE the database (no text leaves Oracle) ...")
            await _run(mcp,
                f"UPDATE documents SET embedding = {indb_embed_expr('content')}",
                "in-db embeddings generated")
        else:
            print("Embedding documents via OpenAI fallback ...")
            client = AsyncOpenAI(api_key=config.OPENAI_API_KEY or None)
            emb = await client.embeddings.create(model=config.EMBED_MODEL, input=[c for (_t, c) in DOCS])
            for (t, _c), d in zip(DOCS, emb.data):
                await mcp.run_sql(
                    f"UPDATE documents SET embedding = TO_VECTOR('{vector_literal(d.embedding)}') "
                    f"WHERE title = {sql_str(t)}")
            print("  · fallback embeddings generated")

        await mcp.run_sql("COMMIT")
        print(f"\nDone. Seed complete ({mode}).")


if __name__ == "__main__":
    asyncio.run(main())
