-- ============================================================================
--  Private RAG on Oracle 26ai — reference schema
--  documents.embedding uses VECTOR(*, FLOAT32) so it holds either the in-DB
--  ONNX model's vectors (e.g. 384-dim) or the OpenAI fallback's (1536-dim).
-- ============================================================================

CREATE TABLE documents (
  doc_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      VARCHAR2(160),
  content    VARCHAR2(4000),
  embedding  VECTOR(*, FLOAT32)
);

-- In-database embedding (no text leaves Oracle) once an ONNX model is loaded:
--   UPDATE documents SET embedding = VECTOR_EMBEDDING(DOC_MODEL USING content AS data);

-- Retrieval, embedding the QUERY inside the database too:
--   SELECT title,
--          VECTOR_DISTANCE(embedding, VECTOR_EMBEDDING(DOC_MODEL USING :q AS data), COSINE) AS distance,
--          content
--   FROM   documents
--   ORDER BY VECTOR_DISTANCE(embedding, VECTOR_EMBEDDING(DOC_MODEL USING :q AS data), COSINE)
--   FETCH  APPROX FIRST 3 ROWS ONLY;
